### ISSUE TITLE
‘string’ in namespace ‘std’ does not name a type in cstring

### ISSUE THREAD

**Issue by techwday** [elibensasson/libSTARK#25]
When trying to compile in Ubuntu 21.04 I get the following error with regards to cstring. If I add #include <string> to MerkleCommitment.hpp then the library compiles.

```
In file included from src/protocols/Ali/common_details/common.hpp:4,
                 from src/protocols/Ali/common_details/common.cpp:1:
src/protocols/common/CryptoCommitment/MerkleCommitment.hpp:17:10: error: ‘string’ in namespace ‘std’ does not name a type
   17 |     std::string toString()const;
      |          ^~~~~~
src/protocols/common/CryptoCommitment/MerkleCommitment.hpp:9:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
    8 | #include <set>
  +++ |+#include <string>
    9 | 
```

**Comment by lovely-necromancer** [comment]
same here.
just created a PR to address this: https://github.com/elibensasson/libSTARK/pull/28

**Comment by rcolomina** [comment]
Just add the include please `#include <string>`, it solves the problem.
